services:
  carmodel-api:
    build: ./carmodel-api
    image: carmodel-api
    container_name: api-carmodel
    platform: linux/amd64
    restart: always
    ports:
      - "4500:3500"
    networks:
      - car-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@postgres:5432/CarmodelDB?schema=public
      - PORT=3500
      # - DATABASE_URL=postgresql://postgres:1234567890@bookingdb:5432/bookingdb?schema=public
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:17.5
    container_name: postgres-carmodel
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: CarmodelDB
    ports:
      - "5870:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - car-network
    restart: unless-stopped

  websetting:
    build: ./websetting
    image: carmodel-web-settingpi
    container_name: web-settingpi
    platform: linux/amd64
    restart: always
    ports:
      - "3500:3000"
    networks:
      - car-network
    depends_on:
      - postgres
    environment:
      # - NEXT_PUBLIC_API=http://192.168.1.118:4500/api/
      # - PORT=3000
      - NEXT_PUBLIC_API=http://192.168.1.118:4500/api/
      - PORT=3000
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_cmVsZXZhbnQtbGl6YXJkLTguY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=sk_test_cKZFsxotq93rEJAnCKlMSFbFxT9IZSfZK8GUjr5aEX

networks:
  car-network:
    driver: bridge
